[package]
name = "advent-of-code-2019-rust"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "day1-part1"
path = "src/day1-part1.rs"

[[bin]]
name = "day1-part2"
path = "src/day1-part2.rs"

[dependencies]
